"use client";

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Download, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function FinanceReportsPage() {
  const handleDownload = () => {
    // Dummy download action
    alert("Downloading report...");
  };

  return (
    <div className="flex-1 space-y-4 pl-4 pr-4">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h2 className="text-3xl font-bold tracking-tight">Financial Reports</h2>
          <p className="text-muted-foreground">Exportable statements, budget records, and compliance data.</p>
        </div>
        <Button onClick={handleDownload}>
          <Download className="mr-2 h-4 w-4" /> Export All
        </Button>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center text-lg">
              <FileText className="mr-2 h-5 w-5 text-blue-500" />
              Q3 Employee Salary Disbursement
            </CardTitle>
            <CardDescription>Prepared on Oct 1, 2026</CardDescription>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground mb-4">Complete log of all salaries, bonuses, and deductions released for Quarter 3.</p>
            <Button variant="outline" className="w-full" onClick={handleDownload}>Download PDF</Button>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center text-lg">
              <FileText className="mr-2 h-5 w-5 text-emerald-500" />
              Annual Expense Claims Report
            </CardTitle>
            <CardDescription>Prepared on Dec 31, 2025</CardDescription>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground mb-4">Reconciled travel, equipment, and departmental expenditures.</p>
            <Button variant="outline" className="w-full" onClick={handleDownload}>Download CSV</Button>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center text-lg">
              <FileText className="mr-2 h-5 w-5 text-purple-500" />
              Tax & Compliance Audit '25
            </CardTitle>
            <CardDescription>Prepared on Jan 14, 2026</CardDescription>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground mb-4">Official tax documentation required for state and federal compliance auditing.</p>
            <Button variant="outline" className="w-full" onClick={handleDownload}>Download XML</Button>
          </CardContent>
        </Card>
      </div>

      <Card className="mt-8">
        <CardHeader>
          <CardTitle>Recent Generate Requests</CardTitle>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Report Name</TableHead>
                <TableHead>Generated By</TableHead>
                <TableHead>Format</TableHead>
                <TableHead>Date</TableHead>
                <TableHead className="text-right">Action</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell className="font-medium">March Payroll Summary</TableCell>
                <TableCell>Jane Smith (Admin)</TableCell>
                <TableCell>PDF</TableCell>
                <TableCell>Mar 31, 2026</TableCell>
                <TableCell className="text-right">
                  <Button variant="ghost" size="sm">Redownload</Button>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-medium">Software Subscriptions '26</TableCell>
                <TableCell>You</TableCell>
                <TableCell>CSV</TableCell>
                <TableCell>Mar 15, 2026</TableCell>
                <TableCell className="text-right">
                  <Button variant="ghost" size="sm">Redownload</Button>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-medium">Q1 Hardware Reimbursables</TableCell>
                <TableCell>You</TableCell>
                <TableCell>PDF</TableCell>
                <TableCell>Feb 28, 2026</TableCell>
                <TableCell className="text-right">
                  <Button variant="ghost" size="sm">Redownload</Button>
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}